version: '3.1'

services:
  postgres:
    image: postgres:11.4
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/entrypoint-init.d:/docker-entrypoint-initdb.d
