version: '3.1'

services:
  postgres:
    image: postgres:11.4
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/entrypoint-init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h postgres -d csv"]
      interval: 10s
      timeout: 5s
      retries: 5

  crm:
    image: golang:1.12.9
    restart: unless-stopped
    ports:
      - 8089:80
    volumes:
      - ./crm_server:/root/crm
    entrypoint: go run /root/crm/server.go
